version: '3.8'

services:
  tuuam-db:
    image: postgres:15-alpine
    container_name: tuuam-postgres
    restart: always
    environment:
      POSTGRES_USER: tuuam_user
      POSTGRES_PASSWORD: tuuam_password
      POSTGRES_DB: tuuam_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tuuam-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tuuam.de
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - tuuam-db
